### ISSUE TITLE
CRITICAL: 'charmap' codec can't decode byte 0x9d in position 5425

### ISSUE THREAD

**Issue by theodox** [pelican-plugins/seo#9]
Installing the pluing via pip and enabling it in `pelicanconf.cpy` results in this error:

      CRITICAL: 'charmap' codec can't decode byte 0x9d in position 5425: character maps to <undefined>

I'm sure it's this plugin, since it started when I added the plugin to a site which generated fine, and it stops if I remove the plugin.

Running Window10 & Python 3.8.5; this was the only plugin added when the error occurs.  I'm guessing it might be something inside of beautiful soup scraping a file in a file with an unexpected encoding.  To be sure I tried this on an empty project created with the pelican quickstart and got the same error.

**Comment by theodox** [comment]
Looking at it further it appears like the output HTML was partially generated - so it might be that the failure is in the writing of the output file...

**Comment by MaevaBrunelles** [comment]
Hi @theodox,

Thanks for your interest on this plugin!

I failed on reproducing your issue. I tried with the same env:
- `Windows 10`
- `python 3.8.5`
- `pelican 4.5.0`
- `pelican 1.0.0`

I did a `pelican-quickstart`, activated the plugin on `pelicanconf.py` and I added a Mardown file. The HTML ouput is well generated including the SEO features. I did not encounter codec errors.

So I need more informations in order to help you:
- Can you send me the complete stacktrace?
- Can you send me the site you're trying to generate? Or at least the file that you tkink is problematic.
- What is the complete path where you execute pelican commands?
- What is the command you execute which raise these error? `pelican content`?

**Comment by kdeldycke** [comment]
I can confirm the issue, and I track it down somewhere in the code behind the `SEO_ENHANCER` option. Deactivating that get rid of the error.

Here is the traceback:
```shell-session
❯ poetry run pelican --debug --verbose ./content
-> SEO plugin initialized
(...)
-> SEO plugin - SEO Report: seo_report.html file created
-> SEO plugin - SEO Enhancement: robots.txt file created
-> Writing /Users/kde/blog/output/feed/atom/index.html
-> Writing /Users/kde/blog/output/feed/index.html
-> Writing /Users/kde/blog/output/category/english/feed/atom/index.html
-> Writing /Users/kde/blog/output/category/english/feed/index.html
-> Writing /Users/kde/blog/output/category/francais/feed/atom/index.html
-> Writing /Users/kde/blog/output/category/francais/feed/index.html
-> Writing /Users/kde/blog/output/category/front-page/feed/atom/index.html
-> Writing /Users/kde/blog/output/category/front-page/feed/index.html
-> Writing /Users/kde/blog/output/tag/python/feed/atom/index.html
-> Writing /Users/kde/blog/output/tag/python/feed/index.html
(...)
-> Writing /Users/kde/blog/output/2020/10/billing-pipeline-critical-time-sensitive-system/index.html
CRITICAL: 'ascii' codec can't decode byte 0xc2 in position 278: ordinal not in range(128)
```

Notice how categories, tags and feeds pages gets created without any issue but as soon as the first article is written, we got encoding errors.

For the context, I'm running Pelican 4.5.0, Python 3.8.6 on macOS Catalina 10.15.7. This can be reproduced as the content and configuration is available at: https://github.com/kdeldycke/kevin-deldycke-blog . The article that is triggering the issue is my last one at: https://github.com/kdeldycke/kevin-deldycke-blog/blob/main/content/posts/billing-pipeline-critical-time-sensitive-system.md . See how it is full of emojis? I'm quite certain it has something to do with the error.

**Comment by kdeldycke** [comment]
Got it:
```python-traceback
> /Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/plugins/seo/seo_enhancer/__init__.py(80)add_html_to_file()
-> html_content = html_file.read()
(Pdb) n
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 278: ordinal not in range(128)
> /Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/plugins/seo/seo_enhancer/__init__.py(80)add_html_to_file()
-> html_content = html_file.read()
(Pdb) l
 75  	        """
 76  	
 77  	        import pdb; pdb.set_trace()
 78  	
 79  	        with open(path) as html_file:
 80  ->	            html_content = html_file.read()
 81  	            soup = BeautifulSoup(html_content, features="html.parser")
 82  	
 83  	        canonical_tag = soup.new_tag(
 84  	            "link", rel="canonical", href=enhancements.get("canonical_tag")
 85  	        )
(Pdb) html_file
<_io.TextIOWrapper name='/Users/kde/blog/output/2020/10/billing-pipeline-critical-time-sensitive-system/index.html' mode='r' encoding='US-ASCII'>
(Pdb) 
```

**Comment by kdeldycke** [comment]
I'm working on a fix at: https://github.com/pelican-plugins/seo/pull/13

**Comment by MaevaBrunelles** [comment]
I still fail to reproduce the issue. If I add emoji on my sandbox site, I don't encounter encode issue. Same thing when I generate your site and the incriminated page, the HTML generation is well done.

So I guess my environment is full settled as UTF-8, which is why it's working properly; unlike yours, which can use other encoding at some point. 

In any case it's an issue, and I believe that your PR fix it, but I would like to have a test that confirm this (as I'm unable to reproduce it as a customer user). I'll work on it, but I encounter another issue when I try to generate your site, so I'm looking at this.

**Comment by kdeldycke** [comment]
Thanks @MaevaBrunelles for the update! I'll look into https://github.com/getpelican/pelican/issues/2814 .

**Comment by MaevaBrunelles** [comment]
Alright, I've finally found the true root cause of this issue 🎉

You encounter this error because set `LOCALE='C'` is set in `pelicanconf.py`, which doesn't handle some characters (typically emojis I guess).

I didn't have this issue because when I did `pelican-quickstart`, I had a basic `pelicanconf.py` without the `LOCALE` setting. And as explained in the [Pelican documentation](https://docs.getpelican.com/en/stable/settings.html#LOCALE), default is the system locale, which is `fr_FR.UTF-8` in my case. So generating your file works great for me.

Noting that, my feeling is that this is not the responsibility of my plugin to modify encoding to counter what people configure.  
Did you consider to update `LOCALE` to `en_US.UTF-8`? I tested it on my side and your site is well generated:
`Done: Processed 350 articles, 0 drafts, 4 pages, 0 hidden pages and 0 draft pages in 175.00 seconds.`

**Comment by kdeldycke** [comment]
😨 Oooooh, you're right. I somehow overlooked this... 🤦‍♂️

Just tried it at https://github.com/kdeldycke/kevin-deldycke-blog/commit/c9d506782c175ce283eea5ca650a7373fdf2eadb . And indeed, it eliminate the issue. I do not need the changes I proposed at https://github.com/pelican-plugins/seo/pull/13 .

Now this `LOCALE` variable was set 8 years ago, right at the beginning of my blog: https://github.com/kdeldycke/kevin-deldycke-blog/commit/ec2b640e609a27a30707999edf2a5612da6f40b1#diff-d65cf0288f1d9a86915f40ad4e588bbbb59fd7b1f932ea9beaa39927e3bcf18cR11

I don't know where I got this but I guess it is an old default I inherited from the early days of Pelican. But I can't trace it back from the original `pelican-quickstart` helper script: https://github.com/getpelican/pelican/commit/1edbe044a28cd31e5ccde0f67569f5c5dcbfe210 . So it might come from a copy'n'paste of the sample configuration (see: https://github.com/getpelican/pelican/commit/ef77847762111d165cba14c65dfe5dfb11425530 ).

Anyway, huge thanks @MaevaBrunelles for your incredible patience and tenacity. 🤩 You did an amazing job getting at the bottom of that issue. 😎👍

Now the issue is OK to be closed to me. I'll revise my PR at #13 to remove my unnecessary changes.

**Comment by MaevaBrunelles** [comment]
Amazing!

Thanks for your feedback, without your input this issue would be there for a long time to come. 

@theodox if you ever come back that way, don't hesitate to play with `LOCALE` setting.

**Comment by bertwagner** [comment]
I am experiencing a similar issue:

```
File "...\.venv\lib\site-packages\pelican\plugins\seo\seo_enhancer\__init__.py", line 95, in add_html_to_file
    html_file.write(soup.prettify())
  File "...\python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u02bc' in position 1848: character maps to <undefined>
```

It appears beautiful soup is using my non-UTF-8 system defined codepage.  If I change the above line to:

```
with open(path, "wb") as html_file:
            html_file.write(soup.prettify(encoding="UTF-8"))
```

Everything works great.  

I am using 
- Windows 10, set to a non-unicode codepage
- pelican 4.5.1 (also tested with 4.5.0), 
- python 3.8.2

I don't have a LOCALE variable defined in my pelicanconf.py, but after reading the above thread I tried adding it with various UTF8 encodings but still experience the same issue.

Does the SEO plugin somehow import the LOCALE that should be used from the pelicanconf.py file?  Should that encoding somehow be set as the default for BeautifulSoup?  I didn't see anything in the library that does that, but I very well could be missing it.

Happy to help work on a fix if it's needed.

**Comment by MaevaBrunelles** [comment]
> It appears beautiful soup is using my non-UTF-8 system defined codepage.
> I don't have a LOCALE variable defined in my pelicanconf.py

Indeed, that's how Pelican works. If you don't have a `LOCALE` defined, Pelican will use the locale from your system, in your case a non-unicode locale. If your articles contain some unicode characters, it's normal that the generation fails.

But it's not normal if you have specified a `LOCALE`. So, which values did you try? Did you try `en_US.UTF-8 `?

**Comment by bertwagner** [comment]
I have tried the following values for LOCALE: 
- "en_US.utf8"
- "fr_FR.utf8"
- "en_US.UTF-8"
- "fr_FR.UTF-8" 

The first two in that list are what appear if I run `locale -a` on my machine. The last two values I tried because I've seen them in this thread.  I receive the error if I try any of the above 4 values or omit the LOCALE setting entirely.

My pelicanconf.py: https://gist.github.com/bertwagner/b48245d9ff222055ddc459936e6b67ff
The post the seo enhancer fails on: https://gist.githubusercontent.com/bertwagner/8e0cece822b6e3d789418405252b4fd1/raw/adc1c726543a8d3a0e7e56a1c053626274d219e7/homoglyph-post.md

**Comment by avaris** [comment]
Just wanted to chime in. This is tangentially related to `LOCALE` config in `pelicanconf.py`. [`open`](https://docs.python.org/3/library/functions.html#open) defaults to [`locale.getpreferredencoding()`](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding), which depends on system settings obviously:

```console
$ LANG=en_US.iso88591 python3 -c "print(open('x').encoding)"
ISO-8859-1
$ LANG=en_US.utf8 python3 -c "print(open('x').encoding)"
UTF-8
```

defining `LOCALE` prompts pelican to do a `setlocale` basically, which can override system defaults:

```console
$ LANG=en_US.iso88591 python3 -c "import locale; locale.setlocale(locale.LC_ALL, 'en_US.utf8'); print(open('x').encoding)"
UTF-8
```

Sadly, things are not as nice on Windows (I'm guessing @bertwagner is using Windows). As far as I know, there is no way of forcing UTF-8 encoding by setting locales. That is why `pelican` explicitly sets encoding to `utf-8` in all I/O operations (see: [here](https://github.com/getpelican/pelican/blob/e3c7a915e500e17b668ddebfb1cc7e30673dbf33/pelican/writers.py#L210), [here](https://github.com/getpelican/pelican/blob/e3c7a915e500e17b668ddebfb1cc7e30673dbf33/pelican/utils.py#L220), [here](https://github.com/getpelican/pelican/blob/e3c7a915e500e17b668ddebfb1cc7e30673dbf33/pelican/readers.py#L250) to list a few). I'd suggest doing the same here too.

**Comment by kdeldycke** [comment]
Feel free to revives my old commits as you need it:
* https://github.com/pelican-plugins/seo/commit/a3f4bb474da5c0960d163123fc35dd06b8782976
* https://github.com/pelican-plugins/seo/commit/32e9802e4c246226f15c1bec27210254c0ac6479#diff-e3a731ef0799071cffd662faed1aee9ae44cc30d50a6ac515e5a2bd3f5bb6d7e

**Comment by MaevaBrunelles** [comment]
I failed to reproduce this issue with my Windows 10 set up, but as encoding seems a little bit tricky on Windows, let's follow @avaris recommandations and do as Pelican does. Better safe than sorry :)

@kdeldycke I can't cherry-pick your commits. Feel free to reopen your PR is you feel like it, otherwise I'll create it.

**Comment by justinmayer** [comment]
One approach might be to:
1. Add Windows to the CI testing matrix (see Pelican's configuration, [part 1](https://github.com/getpelican/pelican/blob/master/.github/workflows/main.yml#L30) and [part 2](https://github.com/getpelican/pelican/blob/master/.github/workflows/main.yml#L55-L62)).
2. Add a related test that fails when run in above CI test environment.
3. Fix the code and ensure that the above failing test now passes in CI. ✨

**Comment by avaris** [comment]
@MaevaBrunelles are you using WSL (Windows Subsystem for Linux) for testing? If so try the good old `cmd.exe`. That should easily reproduce it:

```console

**Comment by MaevaBrunelles** [comment]
@avaris I test directly on a Windows system. And yes, if I run the command you gave, it failed. But I don't really see the point with Pelican, because if I run a `pelican content` with a file including `u263a` character, the generation works well on my Windows.

@justinmayer It might be a good approach, but I don't see how to reproduce this case in a CI context. It's not only about Windows, but it's about a Windows with a non UTF-8 default character set.

So if you guys have a better understanding on this issue, feel free to open a PR; on my side I'll just force UTF-8 in order to avoid any future tricky system configuration.
